USE [master]
GO

/****** Object:  Database [DBA]    Script Date: 4/29/2022 4:09:28 PM ******/
DECLARE @sql_string AS NVARCHAR(MAX)
DECLARE @ComputerName NVARCHAR(100)=   (SELECT CONVERT(NVARCHAR(100),SERVERPROPERTY('MachineName')))
DECLARE @InstanceName NVARCHAR(100)=   (SELECT CONVERT(NVARCHAR(100),SERVERPROPERTY('ServerName')))
DECLARE @mdf_drive CHAR(1) = 'M'
DECLARE @ldf_drive CHAR(1) = 'L'

SELECT REPLACE(@InstanceName,@ComputerName+'\','')

DECLARE @folder_name NVARCHAR(100)= IIF(@ComputerName=@InstanceName,'',REPLACE(@InstanceName,@ComputerName+'\',''))

SET @folder_name = IIF(ISNULL(@folder_name,'')!='' AND RIGHT(@folder_name,1)!='\',@folder_name+'\',@folder_name)

/****** Object:  Database [DBA]    Script Date: 4/29/2022 4:09:28 PM ******/
SET @sql_string = 'CREATE DATABASE [DBA]'
SET @sql_string += ' CONTAINMENT = NONE'
SET @sql_string += ' ON  PRIMARY'
SET @sql_string += '( NAME = N''DBA'', FILENAME = N'''+@mdf_drive+':\'+@folder_name+'Data\DBA.mdf'' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )'
SET @sql_string += ' LOG ON' 
SET @sql_string += ' ( NAME = N''DBA_log'', FILENAME = N'''+@ldf_drive+':\'+@folder_name+'Logs\DBA_log.ldf'', SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )'
SET @sql_string += ' WITH CATALOG_COLLATION = DATABASE_DEFAULT'

RAISERROR('@sql_string: %s',0,1,@sql_string) WITH NOWAIT
EXEC sp_executesql @sql_string

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBA] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [DBA] SET ANSI_NULLS ON 
GO

ALTER DATABASE [DBA] SET ANSI_PADDING ON 
GO

ALTER DATABASE [DBA] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [DBA] SET ARITHABORT ON 
GO

ALTER DATABASE [DBA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBA] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [DBA] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [DBA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBA] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [DBA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBA] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [DBA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBA] SET RECOVERY FULL 
GO

ALTER DATABASE [DBA] SET  MULTI_USER 
GO

ALTER DATABASE [DBA] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [DBA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBA] SET  READ_WRITE 
GO

